import type { Metadata } from "next";

import { LegalDocument } from "@/components/marketing/legal-document";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: "How Verdikt collects, uses, and protects your data.",
};

/**
 * Privacy Policy. Content is scoped to what the product actually does — VIN
 * lookups, AI-written report narratives, Supabase-backed accounts — rather
 * than generic boilerplate, so the policy stays true as the product evolves.
 */
export default function PrivacyPage() {
  return (
    <LegalDocument
      title="Privacy Policy"
      updated="July 31, 2026"
      intro="This policy explains what information Verdikt collects when you use the product, why we collect it, and the choices you have. It applies to the Verdikt website and application."
      sections={[
        {
          heading: "Information we collect",
          body: [
            "We collect information you provide directly and information generated by using the product:",
            [
              "Account information — email address and authentication data, handled by our identity provider.",
              "VIN lookups — the vehicle identification numbers you submit and the reports generated from them.",
              "Usage data — pages viewed, features used, and basic device/browser information, for reliability and product improvement.",
            ],
          ],
        },
        {
          heading: "How we use it",
          body: [
            [
              "To generate and deliver the vehicle verdicts, reports, and AI-written analysis you request.",
              "To maintain your account, watchlist, and saved report history.",
              "To operate, secure, and improve the product — including detecting abuse and diagnosing failures.",
              "To communicate with you about your account or material changes to the service.",
            ],
          ],
        },
        {
          heading: "What we don't do",
          body: [
            "We do not sell your personal information. We do not share the VINs you decode or the reports you generate with dealers, insurers, or other third parties for their own marketing purposes.",
          ],
        },
        {
          heading: "Third-party processing",
          body: [
            "Generating a verdict involves processing through infrastructure providers that host our database and authentication (Supabase) and the AI model that writes report narratives (Anthropic). These providers process data on our behalf under their own security commitments — they don't use your data to train models or for their own purposes.",
          ],
        },
        {
          heading: "Data retention",
          body: [
            "Saved reports and account data persist until you delete them or close your account. You can delete an individual report or your entire account at any time from Settings.",
          ],
        },
        {
          heading: "Your rights",
          body: [
            "Depending on where you live, you may have the right to access, correct, export, or delete your personal information. To exercise any of these rights, contact privacy@verdikt.app.",
          ],
        },
        {
          heading: "Cookies",
          body: [
            "We use essential cookies to keep you signed in and to remember your theme preference. We do not use third-party advertising cookies.",
          ],
        },
        {
          heading: "Changes to this policy",
          body: [
            "If we make a material change to how we handle your data, we'll update this page and, where required, notify you directly.",
          ],
        },
        {
          heading: "Contact",
          body: [
            "Questions about this policy or your data can be sent to privacy@verdikt.app.",
          ],
        },
      ]}
    />
  );
}
